cloud:
  aws:
    credentials:
      access-key: AKIAQEIP3GKFAHYBENSN
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: mmesavicebucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090